services:
  - type: web
    name: ludolang-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    numInstances: 1
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AUTH_COOKIE_DOMAIN
        sync: false
      - key: AUTH_COOKIE_SAME_SITE
        value: "None"
      - key: AUTH_COOKIE_SECURE
        value: "true"

databases:
  - name: ludolang-db
    plan: free
    databaseName: ludolangdb
    user: ludolang
